backend:
  name: git-gateway
  branch: main # Senin dalın "main" olduğu için burası main kalmalı

media_folder: "img" # Resimleri nereye yüklesin?
public_folder: "img"

collections:
  - name: "blog"
    label: "Blog Yazıları"
    files:
      - name: "data"
        label: "Yazılar"
        file: "blog.json" # Verileri bu dosyaya yazacak
        fields:
          - {label: "Yazılar", name: "posts", widget: "list", fields: [
              {label: "Başlık", name: "title", widget: "string"},
              {label: "Tarih", name: "date", widget: "datetime", format: "DD MMM YYYY", date_format: "DD MMM YYYY", time_format: false},
              {label: "Özet", name: "summary", widget: "text"},
              {label: "Kapak Resmi", name: "image", widget: "image"},
              {label: "İçerik", name: "body", widget: "markdown"} 
            ]}